export const FORM_CHANGE_PARAM = 'FORM/CHANGE_PARAM'
export const FORM_CLEAR_SEARCH = 'FORM/CLEAR_SEARCH'

export const SCHEDULE_START_LOAD_CHANNELS = 'SCHEDULE/START_LOAD_CHANNELS'
export const SCHEDULE_LOAD_CHANNELS_SUCCESS = 'SCHEDULE/LOAD_CHANNELS_SUCCESS'
export const SCHEDULE_LOAD_CHANNELS_ERROR = 'SCHEDULE/LOAD_CHANNELS_ERROR'

export const SCHEDULE_START_LOAD_PROGRAM = 'SCHEDULE/START_LOAD_PROGRAM'
export const SCHEDULE_LOAD_PROGRAM_SUCCESS = 'SCHEDULE/LOAD_PROGRAM_SUCCESS'
export const SCHEDULE_LOAD_PROGRAM_ERROR = 'SCHEDULE/LOAD_PROGRAM_ERROR'
export const SCHEDULE_SHOW_PROGRAM = 'SCHEDULE/SHOW_PROGRAM'

